version: '2.1'

services:
  angular-elkhorn:
    image: angular-elkhorn
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js